#!/bin/bash
echo "Menyiapkan Installasi Web server"
sudo apt-get update
echo "Melakukan Installasi Webserver"
sudo apt-get install -y nginx php php-mysql
sudo apt-get install -y unzip
sudo apt-get install -y mysql-server
wget https://github.com/sdcilsy/sosial-media/archive/master.zip
unzip master.zip
sudo rm -Rf /var/www/html/
mkdir -p /var/www/html
sudo mv sosial-media-master/* /var/www/html
cd ~/
chmod +x database
#sudo ./database dbsosmed devopscilsy 1234567890
echo "Setup selesai"
